# Generated by Django 4.2.2 on 2023-06-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_airplane_seatclass_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seatclass',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
