# Generated by Django 4.2.2 on 2023-06-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_airplane_slug_seatclass_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='number_flight',
            field=models.CharField(default=1001, max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
