# Generated by Django 4.2.2 on 2023-06-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_flight_number_flight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ('number_flight',)},
        ),
    ]
