# Generated by Django 4.2.2 on 2023-06-13 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_flight_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='time_departure',
            field=models.TimeField(default=datetime.datetime(2023, 6, 13, 12, 37, 2, 939520, tzinfo=datetime.timezone.utc), verbose_name='время отправления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='data_arrive',
            field=models.DateField(verbose_name='дата и время прибытия'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='data_departure',
            field=models.DateField(verbose_name='дата отправления'),
        ),
    ]
