# Generated by Django 4.2.2 on 2023-06-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_flight_time_departure_alter_flight_data_arrive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='data_arrive',
            field=models.DateTimeField(verbose_name='дата и время прибытия'),
        ),
    ]
