# Generated by Django 4.2.2 on 2023-06-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_flight_data_arrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='number_flight',
            field=models.CharField(max_length=4),
        ),
    ]
