# Generated by Django 4.2.2 on 2023-06-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_flight_number_flight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ('data_departure',)},
        ),
        migrations.AlterField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='content.airplane', verbose_name='самолёт'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_arr', to='content.city', verbose_name='город прибытия'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='content.company', verbose_name='компания'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_dep', to='content.city', verbose_name='город отправления'),
        ),
    ]
