# Generated by Django 4.2.2 on 2023-06-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_flight_options_alter_flight_airplane_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('passport_number', models.CharField(max_length=13, verbose_name='Номер паспорта')),
                ('email', models.CharField(max_length=100, verbose_name='Электронный ящик')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
            ],
        ),
    ]
