# Generated by Django 4.2.2 on 2023-06-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flightscomp', to='content.company', verbose_name='компания'),
        ),
    ]
